#db.driver=org.postgresql.Driver
#db.url= jdbc:postgresql://3e24e-rw.db.pub.dbaas.postgrespro.ru:5432/dbstud
#db.username=vuman_h
#db.password=Ax6IEd4Q$P&Q

db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url= jdbc:sqlserver://localhost:1433;databaseName=projectfinal;encrypt=false
db.username=app_user
db.password=JavaApp@2026